// place files you want to import through the `$lib` alias in this folder.
export {default as Navbar} from './components/navbar/Navbar.svelte'
export {default as Spotlight} from './components/hero/spotlight.svelte'
export {default as Herotext} from './components/hero/herotext.svelte'
export {default as Headers} from './components/hero/headers.svelte'
export {default as Button} from './components/buttons/button.svelte'
export {default as Aboutgrid} from './components/grid/aboutgrid.svelte'
export {default as Servicesgrid} from './components/grid/servicesgrid.svelte'
export {default as Testimonials} from './components/marquee/testimonials.svelte'
export {default as Faq} from './components/faq/faq.svelte'
export {default as Contact} from './components/forms/contact.svelte'
export {default as Footer} from './components/footer/footer.svelte'